[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = 'shanghai'
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
kakarot_sepolia = "https://sepolia-rpc.kakarot.org"

[etherscan]
kakarot_sepolia = { key = "kakarot_sepolia", chain = 1802203764_2, url = "https://api.routescan.io/v2/network/testnet/evm/1802203764_2/etherscan" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
