[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = 'dencun' # Kakarot supports `PUSH0`, `TLOAD` / `TSTORE`
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
kakarot_starknet_sepolia = "https://sepolia-rpc.kakarot.org"

[etherscan]
kakarot_starknet_sepolia = { key = "kakarot_starknet_sepolia", chain = 920637907288165, url = "https://api.routescan.io/v2/network/testnet/evm/920637907288165/etherscan" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
